2021-08-12 15:36:19,974 - DEBUG - app_logger - normalize_data:create_dir_from_web:62  - Function create_dir_from_web(path, url) return page_loader/data/httpbin-org-status-504_files
2021-08-12 15:36:19,975 - DEBUG - app_logger - normalize_data:get_file_name:53  - Added extension HTML
2021-08-12 15:36:19,975 - DEBUG - app_logger - normalize_data:get_file_name:54  - Function return httpbin-org-status-504.html
2021-08-12 15:36:19,975 - DEBUG - app_logger - web_requests:get_response_server:20  - Request to https://httpbin.org/status/504
2021-08-12 15:36:20,526 - ERROR - app_logger - page_loader:main:34  - HTTP Error occured
Traceback (most recent call last):
  File "/home/serggi0/hex3/python-project-lvl3/page_loader/scripts/page_loader.py", line 21, in main
    result = download(args.output, args.url)
  File "/home/serggi0/hex3/python-project-lvl3/page_loader/page_loader.py", line 78, in download
    _, web_page_path = write_web_content(dir_to_download, url, flag='web_page')
  File "/home/serggi0/hex3/python-project-lvl3/page_loader/web_requests.py", line 39, in write_web_content
    response = get_response_server(url)
  File "/home/serggi0/hex3/python-project-lvl3/page_loader/web_requests.py", line 23, in get_response_server
    response.raise_for_status()
  File "/home/serggi0/hex3/python-project-lvl3/.venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: GATEWAY TIMEOUT for url: https://httpbin.org/status/504
